language: php

branches:
  # Only test the master branch and SemVer tags.
  only:
    - master
    - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: 'SCENARIO=symfony4 DEPENDENCIES="update"'
    - php: 7.1
      env: 'SCENARIO=symfony4'
    - php: 7.0.11
      env: 'DEPENDENCIES="update"'
    - php: 7.0.11
    - php: 5.6
    - php: 5.5
      env: 'SCENARIO=symfony2'
    - php: 5.4
      env: 'SCENARIO=symfony2 DEPENDENCIES="update --prefer-lowest'

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - 'composer scenario "${SCENARIO}" "${DEPENDENCIES-install}"'

script:
  - composer test

after_success:
  - travis_retry php vendor/bin/coveralls -v
